apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: decode-scaler
spec:
  scaleTargetRef:
    name: vllm-decode
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: prometheus
      metricType: AverageValue
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        threshold: "1"
        query: vllm:kv_cache_usage_perc or orch_tokens_in_flight{phase="decode"}
