server:
  persistentVolume:
    enabled: false
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s

extraScrapeConfigs: |
  - job_name: keda
    static_configs:
      - targets:
          - keda-operator.keda.svc.cluster.local:8080
  - job_name: hami
    static_configs:
      - targets:
          - hami-device-plugin-monitor.kube-system.svc.cluster.local:31992
          - hami-scheduler.kube-system.svc.cluster.local:31993

alertmanager:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-pushgateway:
  enabled: false
